[workspace]
resolver = "2"
members = ["xepher-backend"]

[workspace.dependencies]
anyhow = "1.0.98"
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["fs", "macros", "test-util"] }
typed-builder = "0.21.0"
